- name: Deploy zabbix-web
  openshift_raw:
    host: https://192.168.99.104:8443
    verify_ssl: no
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: v1
      kind: DeploymentConfig
      metadata:
        name: zabbix-web-ansible
        labels:
          app: zabbix
          service: zabbix_service
        namespace: demo1
      spec:
        replicas: 1
        template:
          metadata:
            labels:
              app: zabbix
              service: zabbix-web
          spec:
            containers:
              - name: zabbix-web-ansible
                image: "zabbix/zabbix-web-nginx-mysql:centos-4.2-latest"
                env:
                - name: ZBX_SERVER_HOST
                  value: zabbix-server
                - name: PHP_TZ
                  value: Europe/Minsk
                - name: DB_SERVER_HOST
                  value: zabbix-mariadb
                - name: MYSQL_USER
                  value: root
                - name: MYSQL_PASSWORD
                  value: pass

- name: Instll zabbix-web Service
  openshift_raw:
    host: https://192.168.99.104:8443
    verify_ssl: no
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: zabbix-web
        namespace: demo1
      spec:
        selector:
          service: zabbix-web
        ports:
          - name: 80-tcp
            protocol: TCP
            port: 80
            targetPort: 80
        type: ClusterIP

- name: Edit Route zabbix-web
  openshift_raw:
    host: https://192.168.99.104:8443
    verify_ssl: no
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: v1
      kind: Route
      metadata:
        name: zabbix-web
        namespace: demo1
      spec:
        host: zabbix-web-demo1.192.168.99.104.nip.io
        port:
          targetPort: 80-tcp
        to:
          kind: Service
          name: zabbix-web
