- name: Deploy zabbix-agent
  openshift_raw:
    host: https://192.168.99.104:8443
    verify_ssl: no
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: v1
      kind: DeploymentConfig
      metadata:
        name: zabbix-agent-ansible
        labels:
          app: zabbix
          service: zabbix_service
        namespace: demo1
      spec:
        replicas: 1
        template:
          metadata:
            labels:
              app: zabbix
              service: zabbix-agent
          spec:
            containers:
              - name: zabbix-agent
                image: zabbix/zabbix-agent:centos-4.2-latest
                securityContext:
                  privileged: true
                env:
                - name: ZBX_HOSTNAME
                  value: zabbix-server
                - name: ZBX_SERVER_HOST
                  value: zabbix-server
                - name: ZBX_PASSIVESERVERS
                  value: zabbix-server

                  

- name: Instll zabbix-agent service
  openshift_raw:
    host: https://192.168.99.104:8443
    verify_ssl: no
    api_key: "{{ api_key }}"
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: zabbix-agent
        namespace: demo1
      spec:
        selector:
          service: zabbix-agent
        ports:
          - name: 10050-tcp
            protocol: TCP
            port: 10050
            targetPort: 10050
        type: ClusterIP